using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace TMS.PL
{
    public partial class FRM_Projects : DevExpress.XtraEditors.XtraUserControl
    {
        DBTMSEntities dBTMSEntities;
        TB_Projects projects;
        ProjectAdd projectAdd;
        public FRM_Projects()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
          
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            TMS.DBTMSEntities dbContext = new TMS.DBTMSEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Projects.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_Projects.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void btnupdate_Click(object sender, EventArgs e)
        {
            UserDataUpdate();
        }
        public void UserDataUpdate()
        {
            try {
                projects = new TB_Projects();
                dBTMSEntities = new DBTMSEntities();
                gridControl1.DataSource = dBTMSEntities.TB_Projects.ToList();
            }catch(Exception ex)
            {
                MessageBox.Show("خطا في اتصال قاعدة البيانات", "خطا",MessageBoxButtons.OK,MessageBoxIcon.Error);
            }
            }

        private void FRM_USER_Load(object sender, EventArgs e)
        {
            UserDataUpdate();
        }

        private void btnadd_Click(object sender, EventArgs e)
        {
            projectAdd = new ProjectAdd(this);
            projectAdd.id = 0;
            projectAdd.Show();

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void btnedit_Click(object sender, EventArgs e)
        {
            int id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
            TB_Projects project1 = new TB_Projects();
            project1 = dBTMSEntities.TB_Projects.Where(x => x.ID == id).FirstOrDefault();
            ProjectAdd projectAdd = new ProjectAdd(this);
            projectAdd.id = id;
            projectAdd.txtprojectName.Text= project1.ProjectName;
            projectAdd.txtprojectDes.Text = project1.ProjectDes;
            projectAdd.btnSave.Text = "تعديل";
            projectAdd.Show();



        }

        private void btndelete_Click(object sender, EventArgs e)
        {
            var result = MessageBox.Show("هل انت متاكد","تحذير",MessageBoxButtons.YesNo,MessageBoxIcon.Warning);
            if (result == DialogResult.Yes)
            {
                int id = Convert.ToInt32(gridView1.GetFocusedRowCellValue("ID"));
                if (id == 0)
                {
                    MessageBox.Show("لايوجد بيانات لحذفها");

                }
                else
                {
                    TB_Projects projects = new TB_Projects();
                    projects = dBTMSEntities.TB_Projects.Where(x => x.ID == id).FirstOrDefault();
                    dBTMSEntities.Entry(projects).State = EntityState.Deleted;
                    dBTMSEntities.SaveChanges();

                    MessageBox.Show("تم الحذف بنجاح");

                    UserDataUpdate();
                }
            }
           
        }
    }
}
