using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using TMS.PL;
using System.Data.Entity;
namespace TMS
{
    public partial class Form1 : Form
    {
        DBTMSEntities db;
        public Form1()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            loaddatanote();
        }

    

        private void btnhome_Click(object sender, EventArgs e)
        {
            FRM_HOME home = new FRM_HOME();
            home.Dock = DockStyle.Fill;
            pn_content.Controls.Clear();
            pn_content.Controls.Add(home);
            lbstate.Text = "الرئيسية";

        }

        private void btntask_Click(object sender, EventArgs e)
        {
            FRM_Task task = new FRM_Task();
            task.Dock = DockStyle.Fill;
            pn_content.Controls.Clear();
            pn_content.Controls.Add(task);
            lbstate.Text = "المهام";


        }

        private void btnuser_Click(object sender, EventArgs e)
        {
            FRM_USER user = new FRM_USER();
            user.Dock = DockStyle.Fill;
            pn_content.Controls.Clear();

            pn_content.Controls.Add(user);
            lbstate.Text = "المستخدمون";

        }

        private void pn_content_Paint(object sender, PaintEventArgs e)
        {
          
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            FRM_HOME home = new FRM_HOME();
            home.Dock = DockStyle.Fill;
            pn_content.Controls.Clear();
            pn_content.Controls.Add(home);
            loaddatanote();
            lbstate.Text = "الرئيسية";

        }

        private void btnproject_Click(object sender, EventArgs e)
        {
            FRM_Projects projects = new FRM_Projects();
            projects.Dock = DockStyle.Fill;
            pn_content.Controls.Clear();
            pn_content.Controls.Add(projects);
            lbstate.Text = "المشاريع";

        }

        private void simpleButton6_Click(object sender, EventArgs e)
        {
            transitionManager1.StartTransition(gridControl1);
            gridControl1.Visible = true;
            transitionManager1.EndTransition();
            loaddatanote();
        }

        private void gridControl1_MouseLeave(object sender, EventArgs e)
        {
            transitionManager1.StartTransition(gridControl1);
            gridControl1.Visible = false;
            transitionManager1.EndTransition();
        }
        private void loaddatanote()
        {
            try
            {
                db = new DBTMSEntities();
                List<TB_Note> notes = db.TB_Note.Where(x => x.Note_User == lbusername.Text || x.Note_Manger == lbusername.Text).ToList();
                gridControl1.DataSource = notes;
                lNotesCount.Text = notes.Count.ToString();
            }

            catch
            {

            }

        }

        private void lbusername_Click(object sender, EventArgs e)
        {

        }

        private void lNotesCount_Click(object sender, EventArgs e)
        {
       
        }

        private void tileView1_DoubleClick(object sender, EventArgs e)
        {
       
                int id = Convert.ToInt32(tileView1.GetFocusedRowCellValue("ID"));
     
              
                    TB_Note Note = new TB_Note();
                     Note   = db.TB_Note.Where(x => x.ID == id).FirstOrDefault();
                    db.Entry(Note).State = EntityState.Deleted;
                    db.SaveChanges();
                    loaddatanote();



                }

        private void timer1_Tick(object sender, EventArgs e)
        {
            loaddatanote();
        }

        private void timer2_Tick(object sender, EventArgs e)
        {

        }

        private void timer3_Tick(object sender, EventArgs e)
        {

        }

        private void btnabout_Click(object sender, EventArgs e)
        {
            FRM_Setting setting = new FRM_Setting();
            setting.Show();
        }

        private void Form1_Deactivate(object sender, EventArgs e)
        {
            //Application.Exit();
        }
    }
        }

